//! gRPC service mirroring the existing HTTP API.
//!
//! Runs alongside axum on a separate port (default 50051) and shares the
//! same job queue, adaptive worker pool, metrics and model registry. Proto
//! code is generated by `build.rs` from `proto/inference.proto`.

use std::sync::Arc;
use std::time::{Duration, Instant};

use tokio::sync::oneshot;
use tonic::{Request, Response, Status};
use uuid::Uuid;

use crate::metrics::Outcome;
use crate::{AppState, InferOptions, InferRequest, Job};

// Generated protobuf / tonic code lives under `inference`.
pub mod inference {
    tonic::include_proto!("inference");
}

use inference::inference_service_server::{InferenceService, InferenceServiceServer};
use inference::{
    HealthRequest, HealthResponse, InferRequest as ProtoInferReq, InferResponse as ProtoInferResp,
    ListModelsRequest, ListModelsResponse, ModelInfo as ProtoModelInfo, Usage as ProtoUsage,
};

// ---------------------------------------------------------------------------
// Conversion helpers
// ---------------------------------------------------------------------------

fn proto_to_request(proto: ProtoInferReq) -> InferRequest {
    let options = proto.options.map(|o| InferOptions {
        max_tokens: o.max_tokens,
        temperature: o.temperature,
        top_p: o.top_p,
    });

    let request_id = if proto.request_id.is_empty() {
        None
    } else {
        Some(proto.request_id)
    };

    InferRequest {
        model: proto.model,
        input: proto.input,
        options,
        request_id,
    }
}

fn response_to_proto(resp: crate::InferResponse) -> ProtoInferResp {
    ProtoInferResp {
        request_id: resp.request_id,
        model: resp.model,
        output: resp.output,
        usage: Some(ProtoUsage {
            latency_ms: resp.usage.latency_ms as u64,
            tokens: resp.usage.tokens,
        }),
        status: resp.status,
    }
}

// ---------------------------------------------------------------------------
// gRPC service implementation
// ---------------------------------------------------------------------------

/// Shared gRPC service state. Wrapped in `Arc` and passed to tonic.
pub struct GrpcInferenceService {
    state: Arc<AppState>,
}

impl GrpcInferenceService {
    pub fn new(state: Arc<AppState>) -> Self {
        Self { state }
    }

    /// Build the tonic `Server`-ready service object.
    pub fn into_server(self) -> InferenceServiceServer<Self> {
        InferenceServiceServer::new(self)
    }
}

#[tonic::async_trait]
impl InferenceService for GrpcInferenceService {
    async fn infer(
        &self,
        request: Request<ProtoInferReq>,
    ) -> Result<Response<ProtoInferResp>, Status> {
        let proto_req = request.into_inner();

        // Validate model name early — same path as the HTTP handler.
        if !self.state.model_registry.contains(&proto_req.model) {
            self.state.metrics.note_validation_error();
            return Err(Status::invalid_argument(format!(
                "unknown model '{}'",
                proto_req.model
            )));
        }

        // Assign or honour the client-supplied request id.
        let request_id = if proto_req.request_id.is_empty() {
            Uuid::new_v4().to_string()
        } else {
            proto_req.request_id.clone()
        };

        let mut infer_req = proto_to_request(proto_req);
        infer_req.request_id = Some(request_id.clone());

        // Enqueue into the shared bounded job queue.
        let (response_tx, response_rx) = oneshot::channel();
        let job = Job {
            request: infer_req,
            response_tx,
        };

        if self.state.job_sender.try_send(job).is_err() {
            self.state.metrics.note_queue_full();
            return Err(Status::unavailable("queue full"));
        }

        // Wait for the worker's response with a timeout.
        let started = Instant::now();
        self.state.metrics.begin_request();
        let timeout_dur = Duration::from_secs(self.state.request_timeout_secs);
        let response = tokio::time::timeout(timeout_dur, response_rx).await;
        let elapsed_ms = started.elapsed().as_millis() as u64;

        match response {
            Ok(Ok(Ok(infer_resp))) => {
                self.state.metrics.finish_request(Outcome::Ok, elapsed_ms);
                Ok(Response::new(response_to_proto(infer_resp)))
            }
            Ok(Ok(Err(err_msg))) => {
                self.state
                    .metrics
                    .finish_request(Outcome::Error, elapsed_ms);
                Err(Status::internal(err_msg))
            }
            Ok(Err(_)) => {
                self.state
                    .metrics
                    .finish_request(Outcome::Error, elapsed_ms);
                Err(Status::internal("worker task cancelled"))
            }
            Err(_) => {
                self.state
                    .metrics
                    .finish_request(Outcome::Timeout, timeout_dur.as_millis() as u64);
                Err(Status::deadline_exceeded(format!(
                    "inference timed out after {}s",
                    self.state.request_timeout_secs
                )))
            }
        }
    }

    async fn health(
        &self,
        _request: Request<HealthRequest>,
    ) -> Result<Response<HealthResponse>, Status> {
        Ok(Response::new(HealthResponse {
            status: "healthy".to_string(),
        }))
    }

    async fn list_models(
        &self,
        _request: Request<ListModelsRequest>,
    ) -> Result<Response<ListModelsResponse>, Status> {
        let models: Vec<ProtoModelInfo> = self
            .state
            .model_registry
            .list()
            .into_iter()
            .map(|m| ProtoModelInfo {
                name: m.name,
                status: m.status,
                device: m.device,
                backend: m.backend,
            })
            .collect();

        Ok(Response::new(ListModelsResponse { models }))
    }
}
