use axum::{
    extract::Json,
    http::StatusCode,
    response::IntoResponse,
    routing::{get, post},
    Extension, Router,
};
use reqwest::Client;
use serde::{Deserialize, Serialize};
use std::net::SocketAddr;
use std::sync::Arc;
use tokio::{
    net::TcpListener,
    sync::{mpsc, oneshot, Semaphore},
    time::{timeout, Duration},
};
use tracing::{debug, error, info};
use tracing_subscriber::EnvFilter;

// Request and response payload types for the HTTP API.
// These structs are serialized/deserialized as JSON by axum/serde.
// Keep these stable: they form the wire contract between clients, the
// Rust gateway, and the C++ inference core.

/// Client-facing request body for POST /infer
/// - model: logical model name
/// - input: input text to run inference on
/// - options: optional inference tuning parameters
#[derive(Serialize, Deserialize, Clone)]
pub struct InferRequest {
    pub model: String,
    pub input: String,
    pub options: Option<InferOptions>,
}

/// Optional parameters to control inference behavior.
/// Not all fields are used by the simple prototype core; they are
/// included for forward-compatibility with a real inference engine.
#[derive(Serialize, Deserialize, Clone)]
pub struct InferOptions {
    pub max_tokens: Option<u32>,
    pub temperature: Option<f32>,
    pub top_p: Option<f32>,
}

/// Gateway / core response shown to clients.
/// - request_id: opaque id generated by the core for tracing
/// - output: textual result from the inference engine
/// - usage: lightweight usage information (latency, token counts)
/// - status: textual status ("ok", "error", ...)
#[derive(Serialize, Deserialize, Clone)]
pub struct InferResponse {
    pub request_id: String,
    pub model: String,
    pub output: String,
    pub usage: Usage,
    pub status: String,
}

/// Minimal usage metrics attached to responses. This is intentionally
/// small and human-readable for the demo phase.
#[derive(Serialize, Deserialize, Clone)]
pub struct Usage {
    pub latency_ms: u128,
    pub tokens: u32,
}

// A JobResult is the worker's return type: either a successful
// InferResponse or a String describing the error.
type JobResult = Result<InferResponse, String>;

// ResponseSender is the oneshot channel used by a worker to deliver
// the result back to the request-handling task.
type ResponseSender = oneshot::Sender<JobResult>;

// Job captures a single inference request plus the channel for the
// worker to send back the result. Jobs are enqueued into a bounded
// mpsc channel to provide simple backpressure at the gateway.
struct Job {
    request: InferRequest,
    response_tx: ResponseSender,
}

// AppState is shared (Arc) into handlers via axum's Extension layer.
// It contains the sending side of the job queue and runtime configuration
// such as the per-request timeout in seconds.
#[derive(Clone)]
struct AppState {
    job_sender: mpsc::Sender<Job>,
    request_timeout_secs: u64,
}

// The entry point: initializes tracing, the task queue and dispatcher,
// and the axum HTTP router. The function is annotated with
// #[tokio::main] to provide an async runtime for the server.
#[tokio::main]
async fn main() {
    tracing_subscriber::fmt()
        .with_env_filter(EnvFilter::from_default_env())
        .init();

    let max_concurrency = 4usize;
    let queue_capacity = 100usize;
    let request_timeout_secs = 10u64;

    // Create a bounded channel used as the task queue. The queue size
    // (queue_capacity) provides simple backpressure: when full, try_send
    // will fail and the HTTP handler will return 503 to the client.
    let (job_sender, job_receiver) = mpsc::channel::<Job>(queue_capacity);

    // Single HTTP client shared by workers to call the inference core
    // over a local RPC boundary. Cloning reqwest::Client is cheap.
    let inference_core_client = Client::new();

    // Spawn the dispatcher loop in the background; it will accept jobs
    // from the queue and spawn worker tasks up to max_concurrency.
    tokio::spawn(dispatcher_loop(job_receiver, max_concurrency, inference_core_client));

    let state = AppState {
        job_sender,
        request_timeout_secs,
    };

    let app = Router::new()
        .route("/health", get(health_handler))
        .route("/metrics", get(metrics_handler))
        .route("/infer", post(infer_handler))
        .layer(Extension(Arc::new(state)));

    // Allow configuring bind address via env var BIND_ADDR (e.g. 127.0.0.1:8080) or PORT (port only)
    let bind_addr = std::env::var("BIND_ADDR").ok().or_else(|| {
        std::env::var("PORT").ok().map(|p| format!("127.0.0.1:{}", p))
    }).unwrap_or_else(|| "127.0.0.1:8080".to_string());

    let addr: SocketAddr = bind_addr.parse().unwrap_or_else(|_| {
        eprintln!("Invalid BIND_ADDR/PORT: {}", bind_addr);
        std::process::exit(1);
    });

    info!(%addr, "starting inference gateway");

    let listener = match TcpListener::bind(addr).await {
        Ok(l) => l,
        Err(e) => {
            // More friendly error message than panic
            if e.kind() == std::io::ErrorKind::AddrInUse {
                eprintln!("Failed to bind to {}: address already in use (is another instance running?).", addr);
                eprintln!("On Windows: run `Get-NetTCPConnection -LocalPort {}` or use Task Manager to stop the process. On Linux: `ss -ltnp | grep {}`.", addr.port(), addr.port());
            } else {
                eprintln!("Failed to bind to {}: {}", addr, e);
            }
            std::process::exit(1);
        }
    };

    if let Err(e) = axum::serve(listener, app).await {
        error!("server error: {}", e);
        std::process::exit(1);
    }
}

// dispatcher_loop runs indefinitely consuming jobs from the queue.
// Implementation notes:
// - A semaphore is used to cap the number of concurrently-running
//   worker tasks (worker_count). This behaves like a worker pool.
// - For each job, a worker task is spawned that calls the inference core
//   and forwards the result back to the original requester via a
//   oneshot channel.
async fn dispatcher_loop(
    mut job_receiver: mpsc::Receiver<Job>,
    worker_count: usize,
    client: Client,
) {
    let semaphore = Arc::new(Semaphore::new(worker_count));
    while let Some(job) = job_receiver.recv().await {
        let permit = semaphore.clone().acquire_owned().await.unwrap();
        let client = client.clone();

        tokio::spawn(async move {
            debug!(request_model = %job.request.model, "dispatching inference job to worker");
            let result = call_inference_core(&client, job.request).await;
            if job.response_tx.send(result).is_err() {
                error!("client response channel dropped before worker completed");
            }
            drop(permit);
        });
    }
}

async fn health_handler() -> impl IntoResponse {
    (
        StatusCode::OK,
        Json(serde_json::json!({"status": "healthy"})),
    )
}

async fn metrics_handler() -> impl IntoResponse {
    // placeholder: replace with Prometheus metrics later
    (StatusCode::OK, "# metrics will be added later\n")
}

// HTTP handler for POST /infer
// Responsibilities:
// 1. Validate/deserialize the incoming request (done by axum's Json extractor)
// 2. Create a oneshot channel for the worker to send back the result
// 3. Try to enqueue the Job. If the bounded queue is full, return 503 quickly
// 4. Wait for the worker's response with a timeout; map outcomes to HTTP codes
async fn infer_handler(
    Extension(state): Extension<Arc<AppState>>,
    Json(payload): Json<InferRequest>,
) -> impl IntoResponse {
    let (response_tx, response_rx) = oneshot::channel();
    let job = Job {
        request: payload.clone(),
        response_tx,
    };

    if let Err(_) = state.job_sender.try_send(job) {
        return (
            StatusCode::SERVICE_UNAVAILABLE,
            Json(serde_json::json!({"status": "queue_full"})),
        );
    }

    let timeout_dur = Duration::from_secs(state.request_timeout_secs);
    match timeout(timeout_dur, response_rx).await {
        Ok(Ok(Ok(infer_resp))) => {
            let v = serde_json::to_value(infer_resp)
                .unwrap_or(serde_json::json!({"status":"ok","output":"serialization_error"}));
            (StatusCode::OK, Json(v))
        }
        Ok(Ok(Err(err_msg))) => (
            StatusCode::INTERNAL_SERVER_ERROR,
            Json(serde_json::json!({"status":"error","message": err_msg})),
        ),
        Ok(Err(_)) => (
            StatusCode::INTERNAL_SERVER_ERROR,
            Json(serde_json::json!({"status":"error","message": "worker task cancelled"})),
        ),
        Err(_) => (
            StatusCode::GATEWAY_TIMEOUT,
            Json(serde_json::json!({"status":"timeout"})),
        ),
    }
}

// call_inference_core performs the synchronous (from the worker's
// perspective) network call to the external inference core. The function
// returns a JobResult which is either the parsed InferResponse or a
// String describing the error. For the prototype the core is a local
// HTTP service listening on 127.0.0.1:8081; in later iterations this
// could be a UNIX socket, shared-memory/FFI call, or gRPC endpoint.
async fn call_inference_core(client: &Client, req: InferRequest) -> JobResult {
    let core_url = "http://127.0.0.1:8081/infer";
    let response = client
        .post(core_url)
        .json(&req)
        .send()
        .await
        .map_err(|err| format!("rpc error: {}", err))?;

    if !response.status().is_success() {
        let status = response.status();
        let text = response
            .text()
            .await
            .unwrap_or_else(|_| "no body".to_string());
        return Err(format!("core returned {}: {}", status, text));
    }

    response
        .json::<InferResponse>()
        .await
        .map_err(|err| format!("failed to decode core response: {}", err))
}
